target 'OBLogger', :exclusive => true do
  pod "OBLogger", :path => ".."
end

target 'Tests', :exclusive => true do
  pod "OBLogger", :path => ".."

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
