//
//  OBViewController.m
//  OBLoggerTest
//
//  Created by Farhad on 8/2/14.
//  Copyright (c) 2014 OneBeat. All rights reserved.
//

#import "OBViewController.h"
#import <OBLOgger/OBLogger.h>

@interface OBViewController ()

@end

@implementation OBViewController

- (void)viewDidLoad
{
    [super viewDidLoad];
    OB_INFO(@"View loaded");
    OB_DEBUG(@"Debug Message");
    OB_WARN(@"Let's throw in a warning Message: WATCH OUT");
    OB_ERROR(@"Error Message but I'm going to make it very long so that we know how it looks when it wraps");
	// Do any additional setup after loading the view, typically from a nib.
    [self subscribeToLoggerNotifications];
}

-(IBAction)createWarning:(id)sender
{
    OB_WARN(@"Warning generated by button");
}

-(IBAction)createError:(id)sender
{
    OB_ERROR(@"Error generated by button");
}


-(void) receivedError: (NSNotification *) notification
{
    NSString *message = notification.object;
    UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"OBLogger Alert" message:message delegate:self cancelButtonTitle:@"Done" otherButtonTitles:nil, nil];
    [alert show];
}
                          
- (void)didReceiveMemoryWarning
{
    [super didReceiveMemoryWarning];
}

- (IBAction)showLog:(id)sender {
    OBLogViewController *logViewer = [OBLogViewController instance];
    [self presentViewController:logViewer animated:YES completion:nil];
}

-(void) subscribeToLoggerNotifications
{
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(receivedError:) name: OBLoggerErrorNotification object:nil];
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(receivedError:) name: OBLoggerWarnNotification object:nil];
}

@end
